# Generated by Django 3.1 on 2020-08-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=200)),
                ('client_last_name', models.CharField(max_length=200)),
                ('client_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_summary', models.TextField()),
                ('job_salary', models.DecimalField(decimal_places=2, max_digits=11)),
                ('job_link', models.TextField()),
                ('job_date_posted', models.IntegerField()),
                ('job_description', models.TextField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_content', models.CharField(max_length=200)),
                ('query_timestamp', models.DateTimeField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_zipcode', models.CharField(max_length=10)),
                ('zip_city', models.CharField(max_length=200)),
                ('zip_state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Query_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.job')),
                ('query_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.query')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.job')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.skill')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='zip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.zip'),
        ),
        migrations.CreateModel(
            name='Client_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.skill')),
            ],
        ),
    ]
