# Generated by Django 3.1 on 2020-08-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.query')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.skill')),
            ],
        ),
        migrations.RemoveField(
            model_name='job_skill',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='job_skill',
            name='skill_id',
        ),
        migrations.DeleteModel(
            name='Client_Skill',
        ),
        migrations.DeleteModel(
            name='Job_Skill',
        ),
    ]
