# Generated by Django 3.1 on 2020-08-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200827_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_timestamp',
            field=models.DateTimeField(),
        ),
    ]
